# Generated by Django 2.2 on 2019-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190418_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'RECRUITER'), (2, 'STUDENT')], default=2),
        ),
    ]
