# Generated by Django 2.2 on 2019-04-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190420_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='job_posting',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organisation'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Candidate'),
        ),
    ]
