# Generated by Django 2.2 on 2019-04-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190420_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.JobPosting'),
        ),
    ]
